### ISSUE TITLE
Send money before determining the exchange rate?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-protocol-stream#44]
If the user sets the `sendMax` amount before knowing the exchange rate, should the packets sent to determine the exchange rate carry money (and be fulfillable)? This would potentially reduce the latency for the first bit of money to get through, because it wouldn't be waiting for multiple round-trips with test packets before sending real money.

On the one hand, this opens things up for connectors to take a larger share of that money, because the sender will set a minimum destination amount of 0. On the other hand, though, connectors that want to do that could just take the same amount of the test packet to influence the minimum exchange rate the sender will set, so it might not make much of a difference.

If a user doesn't want to send money with a minimum acceptable amount of 0, they could just wait until the exchange rate is known before setting the `sendMax`.

**Comment by traviscrist** [comment]
Seems reasonable an a simple way to start the transmission of funds. The risk outlined is there regardless of this being supported since as you mentioned the connectors that want to take a large share could do so anyways by influencing the test packets exchange rate initially.

**Comment by kincaidoneil** [comment]
Would the minimum exchange rate of 0 only apply to those first few test packets, or
would it apply to the entire amount being streamed (in `sendMax`)?

**Comment by emschwartz** [comment]
> Would the minimum exchange rate of 0 only apply to those first few test packets

Yup! As soon as it figured out the exchange rate it would be able to set a more intelligent minimum.

**Comment by traviscrist** [comment]
@emschwartz have you given any more thought to this proposal, with web monetization we can really see this being beneficial. 

If we did implement this do you have any more details on how it would work. Would the connection be created and then packets sent, as they are sent the exchange rate would become clearer and finally be set once a precision is reached? 

Would we keep our packet volley. As is it seems we would see the following behavior:
Sent -> Received 
1 -> 0
1,000 -> 2
1,000,000 -> F08
1,000,000,000 -> F08
1,000,000,000,000 -> F08
Max Packet size is communicated from F08's as 100,000

so if those were all valid packets 2 made it there on the 1,000. If we then follow the current logic we would try 100,000 which ends up failing. 
Then we would try ~66,000 which may succeed but really the connection is already established since we are not holding it for the exchange rate so is it worth keeping the precision probe. 

Maybe instead of the broken up logic we could take the first packet that makes it there and ramp up based on the max packet size. So the next packet would be like 1,000 + 10% of 100,000 = 11,000
11,000 -> 22 so we then ramp it up more to 
21,000 -> 42 
31,000 -> 62 until we hit a T04 and then back off by 1/3. 

I'm curious what your take is on how to combine the exchange rate establishment and sending packets into one smooth flow.

**Comment by SolsticeLLC** [comment]
I believe we are witnessing this issue with the our configuration at Solstice.  We have a Codius host viper.phobosnode.com connected to our ILSP G.AURORA ilsp1.phobosnode.com .  In reviewing the logs from the Codius host and ILSP I can see the this failure related to not being able to determine exchange rate.

All related plugins and modules are at the latest revisions of code as of 10/22/18 20:00:00 UTC

**From the Codius Host: viper.phobosnode.com:**

Oct 22 15:32:38 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:32:38.643Z connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace debug received btp packet. type=TYPE_MESSAGE requestId=3573493118 info=ilp-prepare
Oct 22 15:32:38 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:32:38.643Z connector:ilp-prepare:trace debug handling ilp prepare. sourceAccount=parent destination=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw.FW6223XeFKDzIoOYdrE6FANE~47aaf3f28fe5f4df609ee5c4f2d9d1f1 amount=0 condition=F7ZIDwKeLNsUoK19kQ7RE7JSm7oio6fXF+vjdq55PPs= expiry=2018-10-22T20:33:03.379Z packet=DIIBDAAAAAAAAAAAMjAxODEwMjIyMDMzMDMzNzkXtkgPAp4s2xSgrX2RDtETslKbuiKjp9cX6+N2rnk8+4GCZy5hdXJvcmEuaWxzcC5jaGFubmVsNS5sb2NhbC5Oc2VRNFRqTU8xSlFpU213bWNCRGVLaGJ0S1dYYVBJNm4zaVVoMElfcHh3LkZXNjIyM1hlRktEeklvT1lkckU2RkFORX40N2FhZjNmMjhmZTVmNGRmNjA5ZWU1YzRmMmQ5ZDFmMU44hiJxRjCvnpVr2QNy13WJN2lqlifwrTof3vSjUvgzMgL8yDs0yEiziRDNjaxtdDjTMIgUw2HtBmU3eElXLi48fZeBiEkGMlbwCAFbBqc=
Oct 22 15:32:38 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:32:38.643Z connector:route-builder:trace debug constructing next hop packet. sourceAccount=parent sourceAmount=0 destination=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw.FW6223XeFKDzIoOYdrE6FANE~47aaf3f28fe5f4df609ee5c4f2d9d1f1
Oct 22 15:32:38 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:32:38.643Z connector:route-builder:trace debug determined next hop. nextHop=local
Oct 22 15:32:38 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:32:38.643Z connector:route-builder:trace debug determined local rate. rate=1
Oct 22 15:32:38 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:32:38.644Z connector:ilp-prepare:trace debug sending outbound ilp prepare. destination=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw.FW6223XeFKDzIoOYdrE6FANE~47aaf3f28fe5f4df609ee5c4f2d9d1f1 amount=0
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]: 2018-10-22T20:32:38.647Z ilp-protocol-stream:Server:debug debug got incoming packet for new connection: FW6223XeFKDzIoOYdrE6FANE~47aaf3f28fe5f4df609ee5c4f2d9d1f1 (connectionTag: 47aaf3f28fe5f4df609ee5c4f2d9d1f1)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]: 2018-10-22T20:32:38.647Z ilp-protocol-stream:Server:Connection:error debug remote connection error. code: InternalError, message: Unable to determine path exchange rate
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]: 2018-10-22T20:32:38.648Z ilp-protocol-stream:Server:Connection:error debug destroying connection with error: Error: Remote connection error. Code: InternalError, message: Unable to determine path exchange rate
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at Connection.handleControlFrames (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.ts:552:26)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at Connection.<anonymous> (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.ts:407:12)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at Generator.next (<anonymous>)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at /usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.js:7:71
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at new Promise (<anonymous>)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at __awaiter (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.js:3:12)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at Connection.handlePrepare (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.js:181:16)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at Server.<anonymous> (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/index.ts:265:60)
Oct 22 15:32:38 viper.phobosnode.com codiusd[7828]:     at Generator.next (<anonymous>)
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]:     at /usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.js:7:71
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]:     at new Promise (<anonymous>)
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]:     at __awaiter (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.js:3:12)
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]:     at Connection.handlePrepare (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/connection.js:181:16)
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]:     at Server.<anonymous> (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/index.ts:265:60)
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]:     at Generator.next (<anonymous>)
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]:     at fulfilled (/usr/lib/node_modules/codiusd/node_modules/ilp-protocol-stream/src/index.js:4:58)
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]: 2018-10-22T20:42:33.999Z ilp-protocol-stream:Server:Connection:debug debug not sending connection error because remote is already closed
Oct 22 15:42:34 viper.phobosnode.com codiusd[7828]: 2018-10-22T20:42:33.999Z ilp-protocol-stream:Server:Connection:debug debug got unfulfillable prepare for amount: 0. generated condition: 047f69f8e7f8a7984b696d6196c9db887e52fe4f3d63b9b0c1b39d659bcb9dfd, prepare condition: 5ae039d8ffe94eaf49d018f64cdaf42f59a469299f353d5bb69e6149758699d0
Oct 22 15:42:34 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:42:34.001Z connector:ilp-plugin-mini-accounts[local]:trace debug account NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw: processing btp packet {"type":1,"requestId":2816825450,"data":{"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[14,119,70,57,57,72,103,46,97,117,114,111,114,97,46,105,108,115,112,46,99,104,97,110,110,101,108,53,46,108,111,99,97,108,46,78,115,101,81,52,84,106,77,79,49,74,81,105,83,109,119,109,99,66,68,101,75,104,98,116,75,87,88,97,80,73,54,110,51,105,85,104,48,73,95,112,120,119,0,41,42,204,71,139,231,98,55,28,243,53,111,252,22,26,255,111,128,232,187,229,189,173,4,132,253,77,163,109,115,178,65,14,179,33,1,58,240,204,43,52,6]}}]}}
Oct 22 15:42:34 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:42:34.001Z connector:ilp-plugin-mini-accounts[local]:trace debug packet is authorized, forwarding to host
Oct 22 15:42:34 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:42:34.001Z connector:ilp-plugin-mini-accounts[local]:trace debug received btp packet. type=TYPE_RESPONSE requestId=2816825450 info=ilp-reject
Oct 22 15:42:34 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:42:34.002Z connector:ilp-prepare:trace debug got rejection. cond=WuA52P/p nextHop=local amount=0 code=F99 triggeredBy=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw message=
Oct 22 15:42:34 viper.phobosnode.com moneyd[7739]: 2018-10-22T20:42:34.002Z connector:/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-asym-client/index.js[parent]:trace debug sending btp packet. type=TYPE_RESPONSE requestId=1277144120 info=ilp-reject


**From the ILSP side the associated log entries are:**

0|connector  | 2018-10-22T20:42:33.993Z connector:ilp-plugin-xrp-paychan[g_iov]:trace debug received btp packet. type=TYPE_MESSAGE requestId=2200378455 info=ilp-prepare
0|connector  | 2018-10-22T20:42:33.994Z connector:ilp-prepare:trace debug handling ilp prepare. sourceAccount=g_iov destination=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw.hnI1RW5Q7NQOcQWSP_zNmIdC~d25d3b2442037d628dc02d9ef2bea9af amount=0 condition=WuA52P/pTq9J0Bj2TNr0L1mkaSmfNT1btp5hSXWGmdA= expiry=2018-10-22T20:42:59.734Z packet=DIIBDAAAAAAAAAAAMjAxODEwMjIyMDQyNTk3MzRa4DnY/+lOr0nQGPZM2vQvWaRpKZ81PVu2nmFJdYaZ0IGCZy5hdXJvcmEuaWxzcC5jaGFubmVsNS5sb2NhbC5Oc2VRNFRqTU8xSlFpU213bWNCRGVLaGJ0S1dYYVBJNm4zaVVoMElfcHh3LmhuSTFSVzVRN05RT2NRV1NQX3pObUlkQ35kMjVkM2IyNDQyMDM3ZDYyOGRjMDJkOWVmMmJlYTlhZk4cuuyfWeiVJ8k1S7UaozutusGjkUOvgYrkBG6E0YyQFY05ZaGzxeHRNmGtHrQUn5fWFvb+W5I0IL0hLZzHaRkGrbpMK+r993lMB79/arg=
0|connector  | 2018-10-22T20:42:33.994Z connector:route-builder:trace debug constructing next hop packet. sourceAccount=g_iov sourceAmount=0 destination=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw.hnI1RW5Q7NQOcQWSP_zNmIdC~d25d3b2442037d628dc02d9ef2bea9af
0|connector  | 2018-10-22T20:42:33.994Z connector:route-builder:trace debug determined next hop. nextHop=ilsp
0|connector  | 2018-10-22T20:42:33.994Z connector:route-builder:trace debug determined local rate. rate=1
0|connector  | 2018-10-22T20:42:33.995Z connector:ilp-prepare:trace debug sending outbound ilp prepare. destination=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw.hnI1RW5Q7NQOcQWSP_zNmIdC~d25d3b2442037d628dc02d9ef2bea9af amount=0
0|connector  | 2018-10-22T20:42:34.006Z ilp-plugin-xrp-server:trace account channel5: processing btp packet {"type":1,"requestId":1277144120,"data":{"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[14,119,70,57,57,72,103,46,97,117,114,111,114,97,46,105,108,115,112,46,99,104,97,110,110,101,108,53,46,108,111,99,97,108,46,78,115,101,81,52,84,106,77,79,49,74,81,105,83,109,119,109,99,66,68,101,75,104,98,116,75,87,88,97,80,73,54,110,51,105,85,104,48,73,95,112,120,119,0,41,42,204,71,139,231,98,55,28,243,53,111,252,22,26,255,111,128,232,187,229,189,173,4,132,253,77,163,109,115,178,65,14,179,33,1,58,240,204,43,52,6]}}]}}
0|connector  | 2018-10-22T20:42:34.007Z ilp-plugin-xrp-server:trace packet is authorized, forwarding to host
0|connector  | 2018-10-22T20:42:34.007Z ilp-plugin-xrp-server:trace received btp packet. type=TYPE_RESPONSE requestId=1277144120 info=ilp-reject
0|connector  | 2018-10-22T20:42:34.007Z ilp-plugin-xrp-server:trace got prepare response { type: 14,
0|connector  |   typeString: 'ilp_reject',
0|connector  |   data:
0|connector  |    { code: 'F99',
0|connector  |      triggeredBy:
0|connector  |       'g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw',
0|connector  |      message: '',
0|connector  |      data:
0|connector  |       <Buffer 2a cc 47 8b e7 62 37 1c f3 35 6f fc 16 1a ff 6f 80 e8 bb e5 bd ad 04 84 fd 4d a3 6d 73 b2 41 0e b3 21 01 3a f0 cc 2b 34 06> } }
0|connector  | 2018-10-22T20:42:34.007Z connector:ilp-prepare:trace debug got rejection. cond=WuA52P/p nextHop=ilsp amount=0 code=F99 triggeredBy=g.aurora.ilsp.channel5.local.NseQ4TjMO1JQiSmwmcBDeKhbtKWXaPI6n3iUh0I_pxw message=
0|connector  | 2018-10-22T20:42:34.008Z connector:ilp-plugin-xrp-paychan[g_iov]:trace debug sending btp packet. type=TYPE_RESPONSE requestId=2200378455 info=ilp-reject

**Comment by traviscrist** [comment]
@SolsticeLLC This issue is a discussion about how we can speed up the exchange rate establishment by sending fulfillable packets right away instead of test packets. What you have posted seems like a bug at the codiusd/ILP level which ends up throwing the STREAM 'Unable to determine exchange rate error' 

To keep things clean can you repost it as a separate issue under codiusd so we can debug it there. As part of that posting can you also gather logs with `ilp-protocol-stream*` added to your DEBUG env so if you just have `DEBUG=codiusd*` it would not be `DEBUG=codiusd*,ilp-protocol-stream*` that will provide further insight into why the F99 is being triggered by g.aurora. If a STREAM bug is found then we can post it to the STREAM Project. Thanks!

**Comment by SolsticeLLC** [comment]
My apologies for the intrusion!  Moving to the appropriate location for the issue.  Thanks!
